jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/AbstractSqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/JdbcTypeDescription.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/SqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impl/DB2SqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impl/ExasolSqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impl/GenericSqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impl/HiveSqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impl/ImpalaSqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impl/MysqlSqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impl/OracleSqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impl/PostgreSQLSqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impl/RedshiftSqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impl/SqlServerSqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impl/TeradataSqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/JdbcAdapter.java
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/SqlDialectTest.java

This allows data type changes of the virtual schema import in the adapter.

Replaced IMPORT with IMPORT INTO.

---

jdbc-adapter/doc/supported-dialects.md
jdbc-adapter/integration-test-data/integration-test-sample.yaml
jdbc-adapter/integration-test-data/sybase.sql
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/SqlDialects.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impl/SybaseGenerationVisitor.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impl/SybaseSqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impl/SybaseSqlGenerationVisitor.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/JdbcAdapter.java
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/IntegrationTestConfig.java
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/impl/SybaseSqlDialectIT.java

This pull request merges the changes made for the Sybase Virtual Schema Adapter back into the main repositories `develop` branch.

Sybase Virtual Schema

---

jdbc-adapter/README.md
jdbc-adapter/integration-test-data/run_integration_tests.sh

@andrehacker please review.
Short summary:
* Parameterized hard-coded parts
* Used `readonly` to turn variables into constants.
* Improved readability by separating stages into functions and having a short and precise main function
* Cleaned up handling of temporary directories

Pmi 74 improve travis ci build

---

jdbc-adapter/doc/deploying_the_virtual_schema_adapter.md
jdbc-adapter/doc/developing_an_sql_dialect.md
jdbc-adapter/doc/sql_dialects/db2.md
jdbc-adapter/doc/sql_dialects/exasol.md
jdbc-adapter/doc/sql_dialects/hive.md
jdbc-adapter/doc/sql_dialects/impala.md
jdbc-adapter/doc/sql_dialects/oracle.md
jdbc-adapter/doc/sql_dialects/postgresql.md
jdbc-adapter/doc/sql_dialects/redshift.md
jdbc-adapter/doc/sql_dialects/sql_server.md
jdbc-adapter/doc/sql_dialects/sybase.md
jdbc-adapter/doc/sql_dialects/teradata.md
jdbc-adapter/integration-test-data/integration-test-db2.yaml
jdbc-adapter/integration-test-data/integration-test-sample.yaml
jdbc-adapter/integration-test-data/integration-test-travis.yaml
jdbc-adapter/local/integration-test-config.yaml
jdbc-adapter/pom.xml
jdbc-adapter/virtualschema-jdbc-adapter/src/test/resources/integration/vschema_complete_from_pushdown.json
jdbc-adapter/virtualschema-jdbc-adapter/src/test/resources/integration/vschema_complex_inner_join.json
jdbc-adapter/virtualschema-jdbc-adapter/src/test/resources/integration/vschema_simple_left_outer_join.json

* new tests from the old fork for join pushdowns
This fork will be deleted after this merge.

the last changes from the snehlsen fork joins branch

---

jdbc-adapter/doc/deploying_the_virtual_schema_adapter.md
jdbc-adapter/doc/developing_an_sql_dialect.md
jdbc-adapter/doc/sql_dialects/db2.md
jdbc-adapter/doc/sql_dialects/exasol.md
jdbc-adapter/doc/sql_dialects/hive.md
jdbc-adapter/doc/sql_dialects/impala.md
jdbc-adapter/doc/sql_dialects/oracle.md
jdbc-adapter/doc/sql_dialects/postgresql.md
jdbc-adapter/doc/sql_dialects/redshift.md
jdbc-adapter/doc/sql_dialects/sql_server.md
jdbc-adapter/doc/sql_dialects/sybase.md
jdbc-adapter/doc/sql_dialects/teradata.md
jdbc-adapter/integration-test-data/integration-test-db2.yaml
jdbc-adapter/integration-test-data/integration-test-sample.yaml
jdbc-adapter/integration-test-data/integration-test-travis.yaml
jdbc-adapter/integration-test-data/oracle-testdata.sql
jdbc-adapter/local/integration-test-config.yaml
jdbc-adapter/pom.xml
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/impl/ExasolSqlDialectIT.java
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/impl/OracleSqlDialectIT.java
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/impl/PostgreSQLDialectIT.java

* added join integration tests for exasol, postgres and oracle dialects

Join integration tests

---

jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/redshift/RedshiftMetadataReader.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/redshift/RedshiftTableMetadataReader.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/JdbcAdapterProperties.java

#167: Fixed broken JavaDoc.

---

doc/dialects/postgresql.md

Improvements for the PostgreSQL dialect documentation.
Closes #182

#182 improved PostgreSQL dialect documentation

---

doc/dialects/hive.md

#187: Added string size documentation for Hive.

---

doc/dialects/athena.md
doc/dialects/bigquery.md
doc/dialects/db2.md
doc/dialects/exasol.md
doc/dialects/hive.md
doc/dialects/impala.md
doc/dialects/oracle.md
doc/dialects/postgresql.md
doc/dialects/redshift.md
doc/dialects/sql_server.md
doc/dialects/sybase.md
doc/dialects/teradata.md
doc/user-guide/deploying_the_virtual_schema_adapter.md
jdbc-adapter/integration-test-data/integration-test-db2.yaml
jdbc-adapter/integration-test-data/integration-test-sample.yaml
jdbc-adapter/integration-test-data/integration-test-travis.yaml
jdbc-adapter/local/integration-test-config.yaml
jdbc-adapter/pom.xml
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/AbstractSqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQueryQueryRewriter.java
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/AbstractSqlDialectTest.java
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQueryQueryRewriterTest.java

#189: Fixed `NULL` handling.

---

doc/dialects/athena.md
doc/dialects/bigquery.md
doc/dialects/db2.md
doc/dialects/exasol.md
doc/dialects/hive.md
doc/dialects/impala.md
doc/dialects/oracle.md
doc/dialects/postgresql.md
doc/dialects/redshift.md
doc/dialects/sql_server.md
doc/dialects/sybase.md
doc/dialects/teradata.md
doc/user-guide/deploying_the_virtual_schema_adapter.md
jdbc-adapter/integration-test-data/integration-test-db2.yaml
jdbc-adapter/integration-test-data/integration-test-sample.yaml
jdbc-adapter/integration-test-data/integration-test-travis.yaml
jdbc-adapter/local/integration-test-config.yaml
jdbc-adapter/pom.xml
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/JdbcAdapterFactory.java
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/JdbcAdapterFactoryTest.java

Closes #207 
Haven't found the way to test it with JUnit. I think we need an integration test.
P.S. The build failed because we haven't released the common part yet. We should do it first.

#207: implemented getAdapterVersion()

---

jdbc-adapter/pom.xml

Closes #214.
Task-Url: https://github.com/exasol/virtual-schemas/issues/214

#214: Upgrade dependency to `virtual-schema-common-java` 7.0.0

---

doc/dialects/athena.md
doc/dialects/bigquery.md
doc/dialects/db2.md
doc/dialects/exasol.md
doc/dialects/hive.md
doc/dialects/impala.md
doc/dialects/oracle.md
doc/dialects/postgresql.md
doc/dialects/redshift.md
doc/dialects/sql_server.md
doc/dialects/sybase.md
doc/dialects/teradata.md
doc/user-guide/deploying_the_virtual_schema_adapter.md
jdbc-adapter/integration-test-data/integration-test-db2.yaml
jdbc-adapter/integration-test-data/integration-test-sample.yaml
jdbc-adapter/integration-test-data/integration-test-travis.yaml
jdbc-adapter/local/integration-test-config.yaml
jdbc-adapter/pom.xml
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleColumnMetadataReader.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/BaseColumnMetadataReader.java
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/ColumnMetadataReaderTest.java

#213: removed unsupported data types

---

doc/dialects/athena.md
doc/dialects/bigquery.md
doc/dialects/db2.md
doc/dialects/exasol.md
doc/dialects/hive.md
doc/dialects/impala.md
doc/dialects/oracle.md
doc/dialects/postgresql.md
doc/dialects/redshift.md
doc/dialects/saphana.md
doc/dialects/sql_server.md
doc/dialects/sybase.md
doc/dialects/teradata.md
doc/user-guide/deploying_the_virtual_schema_adapter.md
jdbc-adapter/integration-test-data/integration-test-db2.yaml
jdbc-adapter/integration-test-data/integration-test-sample.yaml
jdbc-adapter/integration-test-data/integration-test-travis.yaml
jdbc-adapter/local/integration-test-config.yaml
jdbc-adapter/pom.xml
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/impala/ImpalaSqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/impala/ImpalaSqlDialectTest.java

#139: implemented missing capabilities for Impala dialect

---

jdbc-adapter/launch/virtual-schema debug listen on port 8000.launch
jdbc-adapter/pom.xml
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/SqlGenerationVisitor.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlGenerationVisitor.java
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/ResultSetMetadataReader.java
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/AbstractSqlDialectFactoryTest.java
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/ResultSetMetadataReaderTest.java

Closes #252.
Task-Url: https://github.com/exasol/virtual-schemas/issues/252

#252: Handling unsupported column in `SELECT *`

---

README.md
doc/dialects/athena.md
doc/dialects/aurora.md
doc/dialects/bigquery.md
doc/dialects/db2.md
doc/dialects/exasol.md
doc/dialects/hive.md
doc/dialects/impala.md
doc/dialects/mysql.md
doc/dialects/oracle.md
doc/dialects/postgresql.md
doc/dialects/redshift.md
doc/dialects/saphana.md
doc/dialects/sql_server.md
doc/dialects/sybase.md
doc/dialects/teradata.md
doc/user-guide/deploying_the_virtual_schema_adapter.md
doc/user-guide/user_guide.md
jdbc-adapter/integration-test-data/integration-test-db2.yaml
jdbc-adapter/integration-test-data/integration-test-sample.yaml
jdbc-adapter/integration-test-data/integration-test-travis.yaml
jdbc-adapter/local/integration-test-config.yaml
jdbc-adapter/pom.xml
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/mysql/MySqlSqlDialect.java
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/mysql/MySqlSqlDialectTest.java

#267: added MySQL catalog support

---

doc/dialects/athena.md
doc/dialects/aurora.md
doc/dialects/bigquery.md
doc/dialects/db2.md
doc/dialects/exasol.md
doc/dialects/hive.md
doc/dialects/impala.md
doc/dialects/mysql.md
doc/dialects/oracle.md
doc/dialects/postgresql.md
doc/dialects/redshift.md
doc/dialects/saphana.md
doc/dialects/sql_server.md
doc/dialects/sybase.md
doc/dialects/teradata.md
doc/user-guide/deploying_the_virtual_schema_adapter.md
jdbc-adapter/integration-test-data/integration-test-db2.yaml
jdbc-adapter/integration-test-data/integration-test-sample.yaml
jdbc-adapter/integration-test-data/integration-test-travis.yaml
jdbc-adapter/local/integration-test-config.yaml
jdbc-adapter/pom.xml
jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/oracle/OracleColumnMetadataReader.java
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/oracle/OracleColumnMetadataReaderTest.java

#270: added support for ROWID column type in Oracle

---

jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/JdbcAdapter.java
jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/JdbcAdapterTest.java

#272: fixed NullPointerException for setProperties request

---

doc/development/remote_debugging.md

#318: Fixed `%jvmoption`. Added troubleshooting information.

---

doc/dialects/athena.md
doc/dialects/aurora.md
doc/dialects/bigquery.md
doc/dialects/db2.md
doc/dialects/exasol.md
doc/dialects/hive.md
doc/dialects/impala.md
doc/dialects/mysql.md
doc/dialects/oracle.md
doc/dialects/postgresql.md
doc/dialects/redshift.md
doc/dialects/saphana.md
doc/dialects/sql_server.md
doc/dialects/sybase.md
doc/dialects/teradata.md
doc/user-guide/user_guide.md
pom.xml
src/main/java/com/exasol/adapter/dialects/mysql/MySqlColumnMetadataReader.java
src/test/java/com/exasol/adapter/dialects/IntegrationTestConstants.java
src/test/java/com/exasol/adapter/dialects/mysql/MySqlColumnMetadataReaderTest.java

#320: hardcoded the size of MySQL data type TEXT

---

pom.xml

#302: removed old integration test dependencies. 

---

doc/user-guide/user_guide.md
pom.xml
src/test/java/com/exasol/adapter/dialects/hive/HiveSqlDialectIT.java

#333: Updated dependencies and fixed incompatibilities issues

---

doc/dialects/athena.md
doc/dialects/aurora.md
doc/dialects/bigquery.md
doc/dialects/db2.md
doc/dialects/hive.md
doc/dialects/impala.md
doc/dialects/mysql.md
doc/dialects/oracle.md
doc/dialects/postgresql.md
doc/dialects/redshift.md
doc/dialects/saphana.md
doc/dialects/sql_server.md
doc/dialects/sybase.md
doc/dialects/teradata.md
doc/user-guide/user_guide.md
pom.xml
src/test/java/com/exasol/adapter/dialects/IntegrationTestConstants.java

#336: fixed broken links

---

README.md
doc/changes/changelog.md
doc/changes/changes-4.0.1.md
doc/development/changelog.md
doc/dialects/athena.md
doc/dialects/aurora.md
doc/dialects/bigquery.md
doc/dialects/db2.md
doc/dialects/hive.md
doc/dialects/impala.md
doc/dialects/mysql.md
doc/dialects/oracle.md
doc/dialects/postgresql.md
doc/dialects/redshift.md
doc/dialects/saphana.md
doc/dialects/sql_server.md
doc/dialects/sybase.md
doc/dialects/teradata.md
doc/user-guide/user_guide.md
pom.xml
src/test/java/com/exasol/adapter/dialects/IntegrationTestConstants.java
tools/version.sh

#346: added changelog.md file, renamed dist file

---

doc/changes/changelog.md
doc/changes/changes-4.0.2.md
doc/dialects/hive.md
pom.xml

Update the Hive kerberos documentation

---

.gitignore
doc/changes/changes-4.0.2.md
doc/dialects/athena.md
doc/dialects/aurora.md
doc/dialects/bigquery.md
doc/dialects/db2.md
doc/dialects/hive.md
doc/dialects/impala.md
doc/dialects/mysql.md
doc/dialects/oracle.md
doc/dialects/postgresql.md
doc/dialects/redshift.md
doc/dialects/saphana.md
doc/dialects/sql_server.md
doc/dialects/sybase.md
doc/dialects/teradata.md
doc/user-guide/user_guide.md
pom.xml
src/test/java/com/exasol/adapter/dialects/IntegrationTestConstants.java

#352: updated dependencies

---

doc/dialects/hive.md

Describes the issue related to Kerberos alias usage instead of principal.

---

.github/workflows/upload_release_asset.yml
README.md
doc/changes/changelog.md
doc/changes/changes-4.0.3.md
doc/dialects/athena.md
doc/dialects/aurora.md
doc/dialects/bigquery.md
doc/dialects/db2.md
doc/dialects/hive.md
doc/dialects/impala.md
doc/dialects/mysql.md
doc/dialects/oracle.md
doc/dialects/postgresql.md
doc/dialects/redshift.md
doc/dialects/saphana.md
doc/dialects/sql_server.md
doc/dialects/sybase.md
doc/dialects/teradata.md
doc/user-guide/user_guide.md
pom.xml
src/test/java/com/exasol/adapter/dialects/IntegrationTestConstants.java
src/test/java/com/exasol/adapter/dialects/mysql/MySqlSqlDialectIT.java

Closes #354 
Closes #355 
Closes #359

Updated documentation

---

doc/changes/changes_4.0.4.md
src/main/java/com/exasol/adapter/dialects/athena/AthenaSqlDialect.java
src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlDialect.java
src/main/java/com/exasol/adapter/dialects/db2/DB2SqlDialect.java
src/main/java/com/exasol/adapter/dialects/generic/GenericSqlDialect.java
src/main/java/com/exasol/adapter/dialects/hive/HiveSqlDialect.java
src/main/java/com/exasol/adapter/dialects/impala/ImpalaSqlDialect.java
src/main/java/com/exasol/adapter/dialects/mysql/MySqlSqlDialect.java
src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlDialect.java
src/main/java/com/exasol/adapter/dialects/postgresql/PostgreSQLSqlDialect.java
src/main/java/com/exasol/adapter/dialects/redshift/RedshiftSqlDialect.java
src/main/java/com/exasol/adapter/dialects/saphana/SapHanaSqlDialect.java
src/main/java/com/exasol/adapter/dialects/sqlserver/SqlServerSqlDialect.java
src/main/java/com/exasol/adapter/dialects/sybase/SybaseSqlDialect.java
src/main/java/com/exasol/adapter/dialects/teradata/TeradataSqlDialect.java
src/test/java/com/exasol/adapter/dialects/dummy/DummySqlDialect.java

#389: Improved connection error handling.

---

doc/changes/changes_4.0.5.md
doc/dialects/oracle.md

#413: Improved documentation on ORACLE_CAST_NUMBER_TO_DECIMAL_WITH_PRECISION_AND_SCALE

---

doc/changes/changes_4.0.5.md
src/main/java/com/exasol/adapter/dialects/oracle/OracleQueryRewriter.java
src/main/java/com/exasol/adapter/dialects/oracle/OracleSqlDialect.java
src/test/java/com/exasol/adapter/dialects/oracle/OracleQueryRewriterTest.java
src/test/java/com/exasol/adapter/dialects/oracle/OracleSqlDialectTest.java

Refactor `OracleQueryRewriter`

---

doc/changes/changes_4.0.5.md
doc/development/developing-sql-dialect/integration_testing_with_containers.md
src/main/resources/META-INF/services/com.exasol.adapter.dialects.SqlDialectFactory

Remove PostgreSQL dialect leftovers

---

.github/workflows/broken_links_checker.yml
README.md
doc/user-guide/dialects.md
doc/user-guide/faq.md

#423: Added check dns entry to the FAQ.

---

doc/changes/changes_6.0.0.md
doc/user-guide/faq.md

#458: Added FAQ entry for outdated views

---

README.md
doc/changes/changelog.md
doc/changes/changes_6.0.0.md
doc/changes/changes_6.0.1.md
doc/dialects/teradata.md
doc/user-guide/dialects.md

#460: Remove Teradata references

---

README.md
doc/changes/changes_6.0.1.md

Updated supported/active-development versions table

---

doc/user-guide/faq.md

#465: Added new FAQ entries

---

doc/dialects/aurora.md
doc/user-guide/dialects.md

#273: Improved Aurora dialect documentation.

---

doc/user-guide/faq.md

#469: Added new FAQ entries related to Kerberos connection

---

.github/workflows/broken_links_checker.yml
doc/changes/changes_6.0.0.md
doc/dialects/aurora.md

#486: Updated Aurora user guide, change link checker

---

.gitattributes
doc/changes/changes_6.0.1.md
doc/dialects/aurora.md
src/test/resources/logging.properties
tools/install_vs.sh

#477: Fix broken links

---

doc/changes/changes_6.0.1.md
doc/user-guide/dialects.md

#476: Enhanced list of dialects
